# Generated by Django 5.0.1 on 2024-02-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_posted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
